//
//  CurrencyFlag.swift
//  iRate
//
//  Created by Sabbir Nasir on 2/8/26.
//

import Foundation

enum CurrencyFlag {
    static func emoji(for currencyCode: String) -> String {
        let upper = currencyCode.uppercased()
        if let region = currencyToRegion[upper] {
            return flagEmoji(for: region)
        }
        return "🌐"
    }

    private static func flagEmoji(for regionCode: String) -> String {
        let base: UInt32 = 127397
        return regionCode.uppercased().unicodeScalars.compactMap { scalar in
            UnicodeScalar(base + scalar.value).map { String($0) }
        }.joined()
    }

    private static let currencyToRegion: [String: String] = [
        "USD": "US",
        "EUR": "EU",
        "GBP": "GB",
        "JPY": "JP",
        "CAD": "CA",
        "AUD": "AU",
        "NZD": "NZ",
        "CHF": "CH",
        "CNY": "CN",
        "CNH": "CN",
        "HKD": "HK",
        "SGD": "SG",
        "INR": "IN",
        "KRW": "KR",
        "SEK": "SE",
        "NOK": "NO",
        "DKK": "DK",
        "PLN": "PL",
        "CZK": "CZ",
        "HUF": "HU",
        "RUB": "RU",
        "TRY": "TR",
        "ZAR": "ZA",
        "BRL": "BR",
        "MXN": "MX",
        "ARS": "AR",
        "CLP": "CL",
        "COP": "CO",
        "PEN": "PE",
        "UYU": "UY",
        "PYG": "PY",
        "VES": "VE",
        "BOB": "BO",
        "GTQ": "GT",
        "HNL": "HN",
        "NIO": "NI",
        "CRC": "CR",
        "PAB": "PA",
        "DOP": "DO",
        "JMD": "JM",
        "TTD": "TT",
        "BSD": "BS",
        "BBD": "BB",
        "BZD": "BZ",
        "BMD": "BM",
        "KYD": "KY",
        "XCD": "AG",
        "AED": "AE",
        "SAR": "SA",
        "QAR": "QA",
        "KWD": "KW",
        "BHD": "BH",
        "OMR": "OM",
        "ILS": "IL",
        "JOD": "JO",
        "EGP": "EG",
        "MAD": "MA",
        "DZD": "DZ",
        "TND": "TN",
        "LYD": "LY",
        "NGN": "NG",
        "GHS": "GH",
        "KES": "KE",
        "UGX": "UG",
        "TZS": "TZ",
        "RWF": "RW",
        "ETB": "ET",
        "XAF": "CM",
        "XOF": "SN",
        "MWK": "MW",
        "MZN": "MZ",
        "BWP": "BW",
        "NAD": "NA",
        "LSL": "LS",
        "SZL": "SZ",
        "AOA": "AO",
        "BIF": "BI",
        "DJF": "DJ",
        "ERN": "ER",
        "SLL": "SL",
        "SLE": "SL",
        "SOS": "SO",
        "SDG": "SD",
        "SSP": "SS",
        "ZWL": "ZW",
        "ZMW": "ZM",
        "PKR": "PK",
        "LKR": "LK",
        "BDT": "BD",
        "NPR": "NP",
        "BTN": "BT",
        "MMK": "MM",
        "THB": "TH",
        "VND": "VN",
        "LAK": "LA",
        "KHR": "KH",
        "MYR": "MY",
        "IDR": "ID",
        "PHP": "PH",
        "MOP": "MO",
        "MNT": "MN",
        "KZT": "KZ",
        "UZS": "UZ",
        "KGS": "KG",
        "TJS": "TJ",
        "TMT": "TM",
        "AFN": "AF",
        "IRR": "IR",
        "IQD": "IQ",
        "SYP": "SY",
        "YER": "YE",
        "GEL": "GE",
        "AMD": "AM",
        "AZN": "AZ",
        "BYN": "BY",
        "UAH": "UA",
        "MDL": "MD",
        "RON": "RO",
        "BGN": "BG",
        "RSD": "RS",
        "MKD": "MK",
        "ALL": "AL",
        "BAM": "BA",
        "HRK": "HR",
        "ISK": "IS",
        "GIP": "GI",
        "FKP": "FK",
        "IMP": "IM",
        "JEP": "JE",
        "GGP": "GG",
        "SHP": "SH",
        "FJD": "FJ",
        "PGK": "PG",
        "WST": "WS",
        "TOP": "TO",
        "SBD": "SB",
        "VUV": "VU",
        "XPF": "PF",
        "TWD": "TW",
        "XDR": "UN"
    ]
}
